
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.io.Serializable;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;


/**
 *
 * @author pacor
 */
public class VMenu extends javax.swing.JFrame implements Serializable {

    private CallbackClientInterface callbackObj;
    private CallbackServerInterface h;
    private ModeloTablaAvisos tablaAvisos;
    private ModeloTablaAvisos tablaNoti;
    private ArrayList<Aviso> avisosCliente;
    private ArrayList<Aviso> notificaciones;
    
    public VMenu() throws RemoteException {
        this.callbackObj = null;
        this.h = null;
        initComponents();
        this.tablaAvisos = new ModeloTablaAvisos();
        this.tablaNoti = new ModeloTablaAvisos();
        avisosCliente = new ArrayList<>();
        notificaciones = new ArrayList<>();
        umbraltxt.setText("0");
    }    
    
    private void muestraExcepcion(String txtExcepcion){
       VAviso va;
       va = new VAviso(this, true, txtExcepcion);
       va.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAvisos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        hostNametxt = new javax.swing.JTextField();
        RMIPorttxt = new javax.swing.JTextField();
        sltEmpresa = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sltTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        umbraltxt = new javax.swing.JTextField();
        btnAnhadir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNoti = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IBEX 35 REQUESTER");
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(246, 246, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel8.setText("IBEX 35 REQUESTER");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Host Name: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Numero de puerto: ");

        tblAvisos.setBackground(new java.awt.Color(247, 247, 251));
        tblAvisos.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tblAvisos.setModel(new ModeloTablaAvisos());
        jScrollPane2.setViewportView(tblAvisos);

        jLabel7.setFont(new java.awt.Font("Verdana Pro Semibold", 0, 16)); // NOI18N
        jLabel7.setText("Avisos pendientes:");

        hostNametxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        RMIPorttxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sltEmpresa.setBackground(new java.awt.Color(226, 226, 251));
        sltEmpresa.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        sltEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACCIONA", "ACENIROX", "ACS", "AENA", "ALMIRALL", "AMADEUS", "ARCELORMIT.", "B.SANTANDER", "BA.SABADELL", "BANKINTER", "BBVA", "CAIXABANK", "CELLNEX", "CIE AUTOMOT.", "ENAGAS", "ENDESA", "FERROVIAL", "FLUIDRA", "GRIFOLS CL.A", "IAG", "IBERDROLA", "INDITEX", "INDRA A", "INM.COLONIAL", "MAPFRE", "MELIA HOTELS", "MERLIN", "NATURGY", "PHARMA MAR", "R.E.C.", "REPSOL", "SIEMENS GAME", "SOLARIA", "TELEFONICA", "VISCOFAN", " " }));
        sltEmpresa.setAutoscrolls(true);
        sltEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Empresa:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tipo de operación:");

        sltTipo.setBackground(new java.awt.Color(226, 226, 251));
        sltTipo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        sltTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Compra", "Venta" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Umbral de acción:");

        umbraltxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        btnAnhadir.setBackground(new java.awt.Color(214, 214, 250));
        btnAnhadir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAnhadir.setText("Añadir Aviso");
        btnAnhadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhadirActionPerformed(evt);
            }
        });

        tblNoti.setBackground(new java.awt.Color(247, 247, 255));
        tblNoti.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tblNoti.setModel(new ModeloTablaAvisos());
        jScrollPane1.setViewportView(tblNoti);

        btnSalir.setBackground(new java.awt.Color(214, 214, 250));
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana Pro Semibold", 0, 16)); // NOI18N
        jLabel9.setText("Notificaciones recibidas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hostNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RMIPorttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(sltTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(sltEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(umbraltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAnhadir))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(hostNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RMIPorttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sltEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sltTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(umbraltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAnhadir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        try {
            // TODO add your handling code here:
            if(h!=null)
                h.unregisterUsrForCallback(callbackObj);
        } catch (RemoteException e) {
            muestraExcepcion("Error al salir: "+ e);
        }
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAnhadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhadirActionPerformed
        if(hostNametxt.getText().isEmpty() || RMIPorttxt.getText().isEmpty() || umbraltxt.getText().isEmpty())
        muestraExcepcion("Alguno de los campos no se ha rellenado inválido");
        else{
            try {
                if(h== null || callbackObj== null){
                    int RMIPort = Integer.parseInt(RMIPorttxt.getText());
                    String hostName = hostNametxt.getText();

                    String registryURL = "rmi://"+hostName+":" + RMIPort + "/callback";

                    h = (CallbackServerInterface)Naming.lookup(registryURL);
                    System.out.println("Lookup completed " );
                    System.out.println("Server said " + h.sayHello());
                    callbackObj = new CallbackClientImpl(this);
                    hostNametxt.setEditable(false);
                    RMIPorttxt.setEditable(false);
                }

                Aviso aviso = new Aviso(sltEmpresa.getItemAt(sltEmpresa.getSelectedIndex()), Double.parseDouble(umbraltxt.getText()),
                    sltTipo.getItemAt(sltTipo.getSelectedIndex()));
                aviso.setCliente(callbackObj);
                if(avisosCliente.contains(aviso)){
                    muestraExcepcion("El aviso ya ha sido introducido previamente");
                }
                else{
                    h.registerForCallback(aviso);
                    avisosCliente.add(aviso);
                    tablaAvisos.setFilas(avisosCliente);
                    tblAvisos.setModel(tablaAvisos);
                }
            } // end try
            catch (NumberFormatException | MalformedURLException | NotBoundException | RemoteException e) {
                muestraExcepcion("Exception in CallbackClient: "+ e);
            }
        }
    }//GEN-LAST:event_btnAnhadirActionPerformed

    public synchronized void recibirNotificacion(Aviso aviso){
        Aviso avisoDel = aviso;
        for(Aviso avisox : avisosCliente){
            if(avisox.getEmpresa().equals(aviso.getEmpresa()) && 
                    avisox.getValor().equals(aviso.getValor()) && 
                    avisox.getTipo().equals(aviso.getTipo())){
                avisoDel = avisox;
            }
        }
        ModeloTablaAvisos ma;
        
        ma=(ModeloTablaAvisos) tblAvisos.getModel();
        ma.borrarFila(this.avisosCliente.indexOf(avisoDel));
        avisosCliente.remove(avisoDel);
        
        ma=(ModeloTablaAvisos) tblNoti.getModel();
        ma.nuevaFila(aviso);
        notificaciones.add(aviso);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RMIPorttxt;
    private javax.swing.JButton btnAnhadir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField hostNametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> sltEmpresa;
    private javax.swing.JComboBox<String> sltTipo;
    private javax.swing.JTable tblAvisos;
    private javax.swing.JTable tblNoti;
    private javax.swing.JTextField umbraltxt;
    // End of variables declaration//GEN-END:variables
}
